# The secrets.properties file is in the resources directory that contains the attributes lmysql.username/password
spring.config.import: classpath:secrets.properties

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/narlock
    username: ${lmysql.username}
    password: ${lmysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver